/**
 * Created by adoug on 2017/3/3.
 */

let cssText = ['/* night */',
    '        .vn-night-body {',
    '            color: #d3d3d3;',
    '            background: #2b3131;',
    '        }',
    '        /*night-background*/',
    '        .vn-night-show .vn-night{',
    '            position: fixed;',
    '            top: 0;',
    '            left: 0;',
    '            bottom: 0;',
    '            right: 0;',
    '            animation: bg-ani 0.5s, disappear-ani 0.5s 1.5s;',
    '            animation-fill-mode: forwards, forwards;',
    '        }',
    '        .vn-night.vn-none {',
    '            display: none;',
    '        }',
    '        .vn-linear{',
    '            background: -ms-linear-gradient(top, #000,  #00002F);',
    '            background:-moz-linear-gradient(top, #000,#00002F);',
    '            background: -webkit-gradient(linear, 0% 0%, 0% 100%, from(#000), to(#00002F));',
    '            background: -webkit-linear-gradient(top, #000, #00002F);',
    '            background: -o-linear-gradient(top, #000, #00002F);',
    '        }',
    '        /*star*/',
    '        .vn-night-show .vn-night .star{position: absolute; top: 0; left: 0; width: 100%; height: 100%; z-index: 98;}',
    '        .vn-night-show .vn-night .star>div{position: absolute; }',
    '        .vn-night-show .vn-night .star>div:nth-child(5n){ width:2px; height: 2px; border-radius: 2px; background:#ddd; -webkit-animation:shine 1s linear 1s infinite; animation:shine 1s linear 1s infinite;}',
    '        .vn-night-show .vn-night .star>div:nth-child(5n+1){ width:4px; height: 4px; border-radius: 4px; background:#fff; -webkit-animation:shine 1s linear 2s infinite; animation:shine 1s linear 2s infinite;}',
    '        .vn-night-show .vn-night .star>div:nth-child(5n+2){ width:2px; height: 2px; border-radius: 2px; background:#fff; -webkit-animation:shine 1s linear 3s infinite; animation:shine 1s linear 3s infinite;}',
    '        .vn-night-show .vn-night .star>div:nth-child(5n+3){ width:4px; height: 4px; border-radius: 4px; background:#fff; -webkit-animation:shine 1s linear 1.5s infinite; animation:shine 1s linear 1.5s infinite;}',
    '        .vn-night-show .vn-night .star>div:nth-child(5n+4){ width:1px; height: 1px; border-radius: 2px; background:#fff; -webkit-animation:shine 1s linear 2.5s infinite; animation:shine 1s linear 2.5s infinite;}',
    '        .vn-night-show .vn-night .star>div:nth-child(1){top: 20%; left: 80%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(2){top: 30%; left: 20%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(3){top: 50%; left: 40%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(4){top: 70%; left: 50%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(5){top: 10%; left: 60%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(6){top: 20%; left: 30%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(7){top: 30%; left: 10%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(8){top: 40%; left: 50%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(9){top: 60%; left: 10%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(10){top: 10%; left: 50%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(11){top: 40%; left: 30%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(12){top: 70%; left: 20%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(13){top: 20%; left: 40%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(14){top: 40%; left: 70%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(15){top: 60%; left: 60%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(16){top: 20%; left: 40%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(17){top: 50%; left: 95%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(18){top: 70%; left: 20%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(19){top: 20%; left: 40%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(20){top: 65%; left: 15%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(21){top: 35%; left: 55%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(22){top: 75%; left: 65%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(23){top: 25%; left: 25%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(24){top: 45%; left: 90%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(25){top: 25%; left: 75%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(26){top: 75%; left: 75%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(27){top: 45%; left: 65%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(28){top: 25%; left: 35%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(29){top: 65%; left: 55%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(30){top: 55%; left: 45%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(31){top: 75%; left: 75%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(32){top: 25%; left: 25%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(33){top: 35%; left: 85%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(34){top: 35%; left: 45%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(35){top: 15%; left: 25%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(36){top: 55%; left: 45%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(37){top: 75%; left: 55%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(38){top: 25%; left: 55%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(39){top: 55%; left: 65%;}',
    '        .vn-night-show .vn-night .star>div:nth-child(40){top: 65%; left: 25%;}',
    '        @-webkit-keyframes shine{0%{opacity:0.5} 100%{opacity: 1}}',
    '        @keyframes shine{0%{opacity:0.5} 100%{opacity: 1}}',
    '        /*moon*/',
    '        .vn-night-show .vn-night .moon{ position: absolute; top:6%; left: 10% ;width: 200px; height: 200px; border-radius: 200px; background:#fff;z-index: 99 ;}',
    '        .vn-night-show .vn-night .shadow{-moz-box-shadow:0 0 100px #fff;  -webkit-box-shadow:0 0 100px #fff;  box-shadow:0 0 100px #fff;}',
    '        /*room*/',
    '        .vn-night-show .vn-night .house{ position: absolute;bottom: 0; left: 20%;width:300px; height: 160px; }',
    '        .vn-night-show .vn-night .house .roof{position: absolute; top: 0; left: 0; width: 0; height: 0;border-left: 150px solid transparent; border-right: 150px solid transparent;border-bottom: 100px solid black;}',
    '        .vn-night-show .vn-night .house .wall{position: absolute; bottom: 0; left:50px; width: 200px; height: 80px; background: black;}',
    '        .vn-night-show .vn-night .house .chimney{position: absolute; top: 10px; left:200px; width: 30px; height: 80px; background: black;}',
    '        .vn-night-show .vn-night .house .window{position: absolute; top: 100px; left:130px; width: 40px; height: 40px; background: yellow;}',
    '        .vn-night-show .vn-night .house .window::before{position: absolute; top: 50%; left: 0 ;content:"";width:40px; height:1px; background:#999;}',
    '        .vn-night-show .vn-night .house .window::after{position: absolute; top: 0; left: 50% ;content:"";width:1px; height:40px; background:#999;}',
    '        .vn-night-show .vn-night .meteor > .star-basic {',
    '            width: 6px;',
    '            height: 6px;',
    '            -webkit-border-radius: 50%;',
    '            -moz-border-radius: 50%;',
    '            border-radius: 50%;',
    '            background: #ffffff;',
    '            position: absolute;',
    '            top: 100px;',
    '            left: 100%;',
    '            box-shadow:  0 0 18px 10px #fff;',
    '            transform-origin: 0 100%;',
    '            transform: rotate(-45deg);',
    '            animation: meteor-ani 0.5s ease-in 0.5s, disappear-ani 1s 1.5s;',
    '            animation-fill-mode: forwards, forwards;',
    '            opacity: 0;',
    '        }',
    '        .vn-night-show .vn-night .meteor > .star-basic::after {',
    '            content: \'\';',
    '            display: block;',
    '            border: 0px solid #fff;',
    '            border-width: 6px 150px 6px 150px;',
    '            border-color: transparent transparent transparent rgba(255, 255, 255, .3);',
    '            ',
    '            top: 3px;',
    '            left: 6px;',
    '        }',
    '        @keyframes meteor-ani{',
    '            0% {',
    '                opacity: 0;',
    '                transform: scale(0) rotate(-45deg) translate(0, 0);',
    '            }',
    '            100% {',
    '                opacity: 1;',
    '                transform: scale(1) rotate(-45deg) translate(-1000px, 0);',
    '            }',
    '        }',
    '        @keyframes bg-ani {',
    '            0% {',
    '                opacity: 0;',
    '                transform: translate(100%, 0);',
    '            }',
    '            100% {',
    '                opacity: 1;',
    '                transform: translate(0, 0)',
    '            }',
    '        }',
    '        @keyframes disappear-ani {',
    '            0% {',
    '                opacity: 1;',
    '                z-index: auto;',
    '            }',
    '            100% {',
    '                opacity: 0;',
    '                z-index: -100;',
    '            }',
    '        }',
    '        /* daytime */',
    '        .vn-daytime-show .vn-daytime {',
    '            position: fixed;',
    '            top: 0;',
    '            left: 0;',
    '            bottom: 0;',
    '            right: 0;',
    '            background: radial-gradient(ellipse at center, rgba(209,228,234,1) 0%,rgba(186,228,244,1) 100%);',
    '            animation: bg-ani 0.5s, disappear-ani 1s 1.8s;',
    '            animation-fill-mode: forwards, forwards;',
    '        }',
    '        .vn-daytime.vn-none {',
    '            display: none;',
    '        }',
    '        .vn-daytime-show .vn-sun {',
    '            position: absolute;',
    '            top: 50%;',
    '            left: 50%;',
    '            margin: -50px 0 0 -50px;',
    '            width: 100px;',
    '            height: 100px;',
    '            border-radius: 50%;',
    '            border: solid 5px #ffff00;',
    '            opacity: 0;',
    '            animation: appear-ani 0.2s 0.5s, disappear-ani 1s 1.8s;',
    '            animation-fill-mode: forwards, forwards;',
    '        }',
    '        .vn-daytime-show .vn-sun .sunshine {',
    '            position: absolute;',
    '            top: 0;',
    '            left: 0;',
    '            width: 100%;',
    '            height: 100%;',
    '        }',
    '        .vn-daytime-show .vn-sun .sunshine-first {',
    '            animation:sunshine-rotate 0.5s linear 1.3s;',
    '            animation-fill-mode: forwards;',
    '        }',
    '        .vn-daytime-show .vn-sun .sunshine-sencond {',
    '            animation: sunshine-rotate 0.5s linear 1.3s;',
    '            animation-fill-mode: forwards;',
    '        }',
    '        .vn-daytime-show .vn-sun .sunshine-sencond > .light-basic {',
    '            opacity: 0;',
    '        }',
    '        .vn-daytime-show .vn-sun .light-basic {',
    '            position: absolute;',
    '            left: -40%;',
    '            top: 50%;',
    '            transform-origin: right;',
    '            width: 90%;',
    '            height: 3px;',
    '            background: linear-gradient(-90deg, transparent 65%, #ffff00 0);',
    '        }',
    '        .vn-daytime-show .vn-sun .light-1 {',
    '            transform: rotate(45deg);',
    '        }',
    '        .vn-daytime-show .vn-sun .light-2 {',
    '            transform: rotate(90deg);',
    '        }',
    '        .vn-daytime-show .vn-sun .light-3 {',
    '            transform: rotate(135deg);',
    '        }',
    '        .vn-daytime-show .vn-sun .light-4 {',
    '            transform: rotate(180deg);',
    '        }',
    '        .vn-daytime-show .vn-sun .light-5 {',
    '            transform: rotate(225deg);',
    '            animation: appear-ani 0.2s 0.7s;',
    '            animation-fill-mode: forwards;',
    '        }',
    '        .vn-daytime-show .vn-sun .light-6 {',
    '            transform: rotate(270deg);',
    '            animation: appear-ani 0.2s 0.9s;',
    '            animation-fill-mode: forwards;',
    '        }',
    '        .vn-daytime-show .vn-sun .light-7 {',
    '            transform: rotate(315deg);',
    '            animation: appear-ani 0.2s 1.1s;',
    '            animation-fill-mode: forwards;',
    '        }',
    '        .vn-daytime-show .hill {',
    '            position: absolute;',
    '            bottom: -70px;',
    '            right: 0;',
    '            width: 100%;',
    '            height: 250px;',
    '            border-top-right-radius: 160%;',
    '            border-top-left-radius: 100%;',
    '            background-color: #adde60;',
    '            z-index: -1;',
    '        }',
    '        .vn-daytime-show .hill::before {',
    '            background-color: #93cc3a;',
    '            border-top-left-radius: 0;',
    '            border-top-right-radius: 100%;',
    '            bottom: -70px;',
    '            content: "";',
    '            height: 110%;',
    '            left: -54px;',
    '            position: absolute;',
    '            transform: rotate(4deg);',
    '            width: 120%;',
    '        }',
    '        .vn-daytime-show .hill::after {',
    '            content: \'\';',
    '            position: absolute;',
    '            bottom: -100px;',
    '            right: -400px;',
    '            width: 120%;',
    '            height: 110%;',
    '            border-top-right-radius: 100%;',
    '            border-top-left-radius: 0%;',
    '            background-color: #94c943;',
    '            -moz-transform: rotate(-12deg);',
    '            -webkit-transform: rotate(-12deg);',
    '            box-shadow: 0 0 25px #cbf191 inset;',
    '        }',
    '        @keyframes sunshine-rotate {',
    '            0% {',
    '                transform: rotate(0);',
    '            }',
    '            100% {',
    '                transform: rotate(180deg);',
    '            }',
    '        }',
    '        @keyframes appear-ani {',
    '            0% {',
    '                opacity: 0;',
    '            }',
    '            100% {',
    '                opacity: 1;',
    '            }',
    '        }'].join("");

let vnNightHtml = ['<div class="moon shadow"></div>',
    '            <div class="star">',
    '                <!-- 10 -->',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <!-- 20 -->',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <!-- 30 -->',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <!-- 40 -->',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '                <div></div>',
    '            </div>',
    '            <div class="meteor">',
    '                <div class="star-basic star1"></div>',
    '            </div>',
    '            <div class="house">',
    '                <div class="roof"></div>',
    '                <div class="wall"></div>',
    '                <div class="chimney"></div>',
    '                <div class="window"></div>',
    '            </div>'].join("");

let vnDaytimeHtml = ['<div class="hill"></div>',
    '           <div class="vn-sun">',
    '            <div class="sunshine sunshine-first">',
    '                <div class="light-basic"></div>',
    '                <div class="light-basic light-1"></div>',
    '                <div class="light-basic light-2"></div>',
    '                <div class="light-basic light-3"></div>',
    '                <div class="light-basic light-4"></div>',
    '            </div>',
    '            <div class="sunshine sunshine-sencond">',
    '                <div class="light-basic light-5"></div>',
    '                <div class="light-basic light-6"></div>',
    '                <div class="light-basic light-7"></div>',
    '            </div>',
    '        </div>'].join("");

export default {
    cssText,
    vnNightHtml,
    vnDaytimeHtml
};